runtime: python312

env_variables:
  SECRET_KEY: "${{ secrets.APP_SECRET_KEY }}"
  DEBUG: "False"
  GOOGLE_MAPS_API_KEY: "${{ secrets.GCP_MAPS_API_KEY }}"

  DB_NAME: "${{ secrets.DB_NAME_SECRET }}"
  DB_USER: "${{ secrets.DB_USER_SECRET }}"
  DB_PASSWORD: "${{ secrets.DB_PASSWORD_SECRET }}"
  DB_HOST: "${{ secrets.DB_HOST_SECRET }}"
  DB_PORT: "${{ secrets.DB_PORT_SECRET }}"

  APPENGINE_URL: "\$(gcloud config get-value project).uc.r.appspot.com"

beta_settings:
  cloud_sql_instances: "${{ secrets.GCP_CLOUD_SQL_INSTANCE }}"

entrypoint: >-
  python manage.py migrate --no-input &&
  gunicorn -b :$PORT fleettrack.wsgi:application

handlers:
- url: /static/
  static_dir: staticfiles_build/
- url: /.*
  script: auto
