runtime: python312
entrypoint: >-
  python manage.py migrate --no-input &&
  gunicorn -b :$PORT fleettrack.wsgi:application

beta_settings:
  cloud_sql_instances: "fleettrack-app-475400:southamerica-east1:fleettrack-db"

handlers:
- url: /static/
  static_dir: staticfiles_build/
- url: /.*
  script: auto

env_variables:
  DEBUG: "False"