# Generated by Django 5.2.5 on 2025-09-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='demission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Demissão'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número da CNH'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
    ]
