from django.urls import path
from .views import (
    DashboardView,
    VehicleListView,
    VehicleCreateView,
    VehicleUpdateView,
    VehicleDeactivateView,
    VehicleReactivateView,
    DriverListView,
    DriverCreateView,
    DriverUpdateView,
    DriverDeactivateView,
    MaintenanceCreateView,
    MaintenanceListView,
    MaintenanceUpdateView,
    MaintenanceCancelView,
    MaintenanceCompleteView,
    RouteCreateView,
    RouteListView,
    RouteUpdateView,
    RouteCancelView,
    RouteReactivateView,
    RouteCompleteView,
    VehicleMaintenanceHistoryView,
    VehicleRouteHistoryView
)

urlpatterns = [
    path('vehicles/<int:pk>/maintenance_history/', VehicleMaintenanceHistoryView.as_view(), name='vehicle-maintenance-history'),
    path('vehicles/<int:pk>/route_history/', VehicleRouteHistoryView.as_view(), name='vehicle-route-history'),
    path('', DashboardView.as_view(), name='dashboard'),
    path('vehicles/', VehicleListView.as_view(), name='vehicle-list'),
    path('vehicles/add/', VehicleCreateView.as_view(), name='vehicle-add'),
    path('vehicles/<int:pk>/update/', VehicleUpdateView.as_view(), name='vehicle-update'),
    path('vehicles/<int:pk>/deactivate/', VehicleDeactivateView.as_view(), name='vehicle-deactivate'),
    path('vehicles/<int:pk>/reactivate/', VehicleReactivateView.as_view(), name='vehicle-reactivate'),
    path('drivers/', DriverListView.as_view(), name='driver-list'),
    path('drivers/add/', DriverCreateView.as_view(), name='driver-add'),
    path('drivers/<int:pk>/update/', DriverUpdateView.as_view(), name='driver-update'),
    path('drivers/<int:pk>/deactivate/', DriverDeactivateView.as_view(), name='driver-deactivate'),
    path('routes/', RouteListView.as_view(), name='route-list'),
    path('routes/add/', RouteCreateView.as_view(), name='route-add'),
    path('routes/<int:pk>/update/', RouteUpdateView.as_view(), name='route-update'),
    path('routes/<int:pk>/cancel/', RouteCancelView.as_view(), name='route-cancel'),
    path('routes/<int:pk>/reactivate/', RouteReactivateView.as_view(), name='route-reactivate'),
    path('maintenance/', MaintenanceListView.as_view(), name='maintenance-list'),
    path('maintenance/add/', MaintenanceCreateView.as_view(), name='maintenance-add'),
    path('maintenance/<int:pk>/update/', MaintenanceUpdateView.as_view(), name='maintenance-update'),
    path('maintenance/<int:pk>/cancel/', MaintenanceCancelView.as_view(), name='maintenance-cancel'),
    path('maintenance/<int:pk>/complete/', MaintenanceCompleteView.as_view(), name='maintenance-complete'),
    path('routes/<int:pk>/complete/', RouteCompleteView.as_view(), name='route-complete'),
]