# Generated by Django 5.2.5 on 2025-09-20 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('license_number', models.CharField(max_length=30, unique=True, verbose_name='Número da CNH')),
                ('admission_date', models.DateField(verbose_name='Data de Admissão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('demission_date', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('disabled', 'Desativado')], default='available', max_length=20, verbose_name='Status')),
                ('mileage', models.PositiveIntegerField(verbose_name='Quilometragem')),
                ('acquisition_date', models.DateField(verbose_name='Data de Aquisição')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.driver', verbose_name='Motorista')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255, verbose_name='Local de Partida')),
                ('end_location', models.CharField(max_length=255, verbose_name='Local de Chegada')),
                ('start_time', models.DateTimeField(verbose_name='Início Programado')),
                ('end_time', models.DateTimeField(verbose_name='Fim Programado')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('in_progress', 'Em Andamento'), ('completed', 'Concluída'), ('canceled', 'Cancelada')], default='scheduled', max_length=20, verbose_name='Status')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.driver', verbose_name='Motorista')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.vehicle', verbose_name='Veículo')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100, verbose_name='Tipo de Serviço')),
                ('start_date', models.DateTimeField(verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(verbose_name='Data de Fim')),
                ('mechanic_shop_name', models.CharField(max_length=100, verbose_name='Nome da Mecânica')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Estimado')),
                ('current_mileage', models.PositiveIntegerField(verbose_name='Quilometragem Atual')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('in_progress', 'Em Andamento'), ('completed', 'Concluída')], default='scheduled', max_length=20, verbose_name='Status')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.vehicle', verbose_name='Veículo')),
            ],
        ),
    ]
