# Generated by Django 5.2.5 on 2025-10-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='route',
            name='fuel_cost',
        ),
        migrations.AddField(
            model_name='route',
            name='actual_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distância Real (km)'),
        ),
        migrations.AddField(
            model_name='route',
            name='estimated_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distância Estimada (km)'),
        ),
        migrations.AddField(
            model_name='route',
            name='estimated_toll_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Pedágio (Est.)'),
        ),
        migrations.AddField(
            model_name='route',
            name='fuel_price_per_liter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço Combustível (R$/L)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='average_fuel_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Consumo Médio (Km/L)'),
        ),
    ]
