# Generated by Django 5.2.5 on 2025-10-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_route_distance_remove_route_fuel_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Revisão Geral', 'Revisão Geral'), ('Troca de Óleo e Filtros', 'Troca de Óleo e Filtros'), ('Troca de Pneus', 'Troca de Pneus'), ('Revisão dos Freios', 'Revisão dos Freios'), ('Alinhamento e Balanceamento', 'Alinhamento e Balanceamento'), ('Troca da Correia Dentada', 'Troca da Correia Dentada')], max_length=100, unique=True, verbose_name='Tipo de Serviço')),
                ('km_threshold', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite KM')),
                ('days_threshold', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite Dias')),
                ('is_active', models.BooleanField(default=True, verbose_name='Alerta Ativo?')),
            ],
            options={
                'verbose_name': 'Configuração de Alerta',
                'verbose_name_plural': 'Configurações de Alertas',
            },
        ),
    ]
