# Generated by Django 5.2.5 on 2025-10-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alertconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertconfiguration',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='Prioridade'),
        ),
    ]
