# Generated by Django 5.2.5 on 2025-09-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_vehicle_latitude_vehicle_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='route',
            name='end_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude de Chegada'),
        ),
        migrations.AlterField(
            model_name='route',
            name='end_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude de Chegada'),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude de Partida'),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude de Partida'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Disponível'), ('on_route', 'Em Rota'), ('maintenance', 'Em Manutenção'), ('disabled', 'Desativado')], default='available', max_length=20, verbose_name='Status'),
        ),
    ]
