# Generated by Django 5.2.5 on 2025-10-31 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_demission_date_and_more'),
        ('dashboard', '0004_alertconfiguration_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertconfiguration',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', verbose_name='Perfil da Empresa'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', verbose_name='Perfil da Empresa'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', verbose_name='Perfil da Empresa'),
        ),
        migrations.AddField(
            model_name='route',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', verbose_name='Perfil da Empresa'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', verbose_name='Perfil da Empresa'),
        ),
        migrations.AlterField(
            model_name='alertconfiguration',
            name='service_type',
            field=models.CharField(choices=[('Revisão Geral', 'Revisão Geral'), ('Troca de Óleo e Filtros', 'Troca de Óleo e Filtros'), ('Troca de Pneus', 'Troca de Pneus'), ('Revisão dos Freios', 'Revisão dos Freios'), ('Alinhamento e Balanceamento', 'Alinhamento e Balanceamento'), ('Troca da Correia Dentada', 'Troca da Correia Dentada')], max_length=100, verbose_name='Tipo de Serviço'),
        ),
    ]
