# Generated by Django 5.2.5 on 2025-10-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
