# Generated by Django 5.2.5 on 2025-10-31 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='demission_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
