# Generated by Django 5.2.5 on 2025-09-08 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('on_route', 'Em Rota'), ('maintenance', 'Em Manutenção')], default='available', max_length=20, verbose_name='Status')),
                ('mileage', models.PositiveIntegerField(verbose_name='Quilometragem')),
                ('acquisition_date', models.DateField(verbose_name='Data de Aquisição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deactivation_date', models.DateField(blank=True, null=True, verbose_name='Data de Desativação')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Motorista')),
            ],
        ),
    ]
