# Generated by Django 5.2.5 on 2025-09-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='deactivation_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Disponível'), ('on_route', 'Em Rota'), ('maintenance', 'Em Manutenção'), ('disabled', 'Desativado')], default='available', max_length=20, verbose_name='Status'),
        ),
    ]
