# Generated by Django 5.2.5 on 2025-09-09 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_vehicle_deactivation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('license_number', models.CharField(max_length=30, unique=True, verbose_name='Número da CNH')),
                ('admission_date', models.DateField(verbose_name='Data de Admissão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('demission_date', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.driver', verbose_name='Motorista'),
        ),
    ]
