# Generated by Django 5.2.5 on 2025-09-16 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_driver_alter_vehicle_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100, verbose_name='Tipo de Serviço')),
                ('start_date', models.DateTimeField(verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(verbose_name='Data de Fim')),
                ('mechanic_shop_name', models.CharField(max_length=100, verbose_name='Nome da Mecânica')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Estimado')),
                ('current_mileage', models.PositiveIntegerField(verbose_name='Quilometragem Atual')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('in_progress', 'Em Andamento'), ('completed', 'Concluída')], default='scheduled', max_length=20, verbose_name='Status')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.vehicle', verbose_name='Veículo')),
            ],
        ),
    ]
