# Generated by Django 5.2.5 on 2025-09-20 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255, verbose_name='Local de Partida')),
                ('end_location', models.CharField(max_length=255, verbose_name='Local de Chegada')),
                ('start_time', models.DateTimeField(verbose_name='Início Programado')),
                ('end_time', models.DateTimeField(verbose_name='Fim Programado')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('in_progress', 'Em Andamento'), ('completed', 'Concluída'), ('canceled', 'Cancelada')], default='scheduled', max_length=20, verbose_name='Status')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.driver', verbose_name='Motorista')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.vehicle', verbose_name='Veículo')),
            ],
        ),
    ]
